### PR TITLE
fix: languageOptions.parser should be an object

### LINKED ISSUE #215: LanguageOptions.parser is not accepting objects
FlatESLintConfig’s `LanguageOptions["parser"]` [should accept an object containing `parse`](https://eslint.org/docs/latest/use/configure/migration-guide#custom-parsers), but it is currently using the `Parser` type from the old config format which is string only.

### PR DESCRIPTION
**Pull request by NotEvenANeko**
`languageOptions.parser` must be an object since 8.37.0

https://github.com/eslint/eslint/pull/16985

close #215

### CODE REVIEW

File: src/flat-config/language-options.d.ts [hunk 1]
```diff
@@ -1,9 +1,5 @@
-import type {
-  EcmaVersion,
-  Parser,
-  ParserOptions,
-  SourceType,
-} from '../parser-options';
+import type { Linter } from 'eslint';
```
Comment (Shinigami92) [inline src/flat-config/language-options.d.ts:1]: We cant do this type import, because `@types/eslint` is only a devDependency https://github.com/Shinigami92/eslint-define-config/blob/629c46bd7b210a693e133281b190a1f0ddd663dc/package.json#L68

Because this project serves all its types without relying on external types, we need to define this manually

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

File: src/flat-config/language-options.d.ts (hunk 1 above)
Comment (Shinigami92) [reply src/flat-config/language-options.d.ts:1]: I see

For the meantime, please use the following workaround:

```ts

type ParserModule =
        | {
              parse(text: string, options?: any): any;
          }
        | {
              parseForESLint(text: string, options?: any): any;
          };

// ...

parser?: Parser | ParserModule;
```

We still need the "old" behavior/Parser type, as we cannot rely that everyone out there has switched instantly to the newest eslint config.
This package sometimes make loose types like this so we do not annoy developers that are not that much up-to-date.

**Review by Shinigami92 — CHANGES_REQUESTED** [review]

File: src/flat-config/language-options.d.ts (hunk 1 above)
Comment (NotEvenANeko) [reply src/flat-config/language-options.d.ts]: fixed

**Review by Shinigami92 — APPROVED** [review]

**Comment by Shinigami92** [comment]
I think I will do the release tomorrow
